"""
Generate efficiency reports for compliance and documentation.
"""

import json
from typing import Any, Optional
from datetime import datetime
from pathlib import Path

from .measure import measure, EfficiencyScore


class EfficiencyReport:
    """Generate and export efficiency reports."""

    def __init__(self, score: EfficiencyScore, model_name: str = "model"):
        self.score = score
        self.model_name = model_name
        self.generated_at = datetime.now().isoformat()

    def to_dict(self) -> dict:
        """Convert report to dictionary."""
        return {
            "report_type": "AI Efficiency Report",
            "version": "1.0",
            "generated_at": self.generated_at,
            "model_name": self.model_name,
            "summary": {
                "efficiency_score": self.score.efficiency,
                "grade": self.score.grade,
                "compliant": self.score.grade in ["A+", "A", "B"],
            },
            "metrics": self.score.to_dict(),
            "methodology": {
                "standard": "EcoAI Lab AI Efficiency Standard v1.0",
                "formula": "Efficiency = Accuracy (%) / Energy (kWh per 1000 queries)",
                "carbon_calculation": f"CO2 = Energy × {self.score.region} grid intensity",
            },
            "recommendations": self._get_recommendations(),
        }

    def _get_recommendations(self) -> list:
        """Generate recommendations based on score."""
        recommendations = []

        if self.score.grade in ["C", "D"]:
            recommendations.append("Consider model quantization to reduce compute requirements")
            recommendations.append("Evaluate smaller model architectures with similar accuracy")
            recommendations.append("Implement batch processing to improve throughput efficiency")

        if self.score.grade == "D":
            recommendations.append("URGENT: Model efficiency is below acceptable threshold")
            recommendations.append("Consider distillation from larger model to smaller one")

        if self.score.co2_per_1k > 10:
            recommendations.append(f"Carbon footprint is high ({self.score.co2_per_1k:.1f}g/1K queries)")
            recommendations.append("Consider deploying in regions with cleaner grid (e.g., France, Norway)")

        if not recommendations:
            recommendations.append("Model efficiency is good. Continue monitoring.")

        return recommendations

    def save(self, path: str) -> None:
        """
        Save report to file.

        Supported formats: .json, .md, .txt
        """
        path = Path(path)

        if path.suffix == ".json":
            self._save_json(path)
        elif path.suffix == ".md":
            self._save_markdown(path)
        else:
            self._save_text(path)

    def _save_json(self, path: Path) -> None:
        """Save as JSON."""
        with open(path, "w") as f:
            json.dump(self.to_dict(), f, indent=2)

    def _save_markdown(self, path: Path) -> None:
        """Save as Markdown."""
        content = f"""# AI Efficiency Report

**Model**: {self.model_name}
**Generated**: {self.generated_at}
**Grade**: {self.score.grade}

## Summary

| Metric | Value |
|--------|-------|
| Efficiency Score | {self.score.efficiency:,.0f} |
| Accuracy | {self.score.accuracy:.1f}% |
| Energy (per 1K queries) | {self.score.kwh_per_1k:.6f} kWh |
| Carbon (per 1K queries) | {self.score.co2_per_1k:.2f}g CO2 |

## Details

- **Hardware**: {self.score.hardware}
- **Region**: {self.score.region}
- **Total Queries Measured**: {self.score.total_queries:,}
- **Total Time**: {self.score.total_time_seconds:.2f}s

## Recommendations

"""
        for rec in self._get_recommendations():
            content += f"- {rec}\n"

        content += """
## Methodology

This report follows the EcoAI Lab AI Efficiency Standard v1.0.

```
Efficiency = Accuracy (%) / Energy (kWh per 1000 queries)
```

---
*Generated by ai-efficiency (https://github.com/ecoailab/ai-efficiency)*
"""

        with open(path, "w") as f:
            f.write(content)

    def _save_text(self, path: Path) -> None:
        """Save as plain text."""
        with open(path, "w") as f:
            f.write(str(self.score))
            f.write("\n\nRecommendations:\n")
            for rec in self._get_recommendations():
                f.write(f"  - {rec}\n")


def report(
    model: Any,
    data: Any,
    labels: Optional[Any] = None,
    model_name: str = "model",
    n_samples: int = 1000,
    hardware: Optional[str] = None,
    region: str = "WORLD",
) -> EfficiencyReport:
    """
    Generate an efficiency report for a model.

    Args:
        model: Model to evaluate
        data: Input data
        labels: Optional ground truth labels
        model_name: Name for the model in the report
        n_samples: Number of samples to measure
        hardware: Hardware type (auto-detected if None)
        region: Region code for carbon intensity

    Returns:
        EfficiencyReport that can be saved to file

    Example:
        >>> from ai_efficiency import report
        >>> r = report(model, test_data, model_name="GPT-4-turbo")
        >>> r.save("efficiency_report.md")
        >>> r.save("efficiency_report.json")
    """

    score = measure(
        model=model,
        data=data,
        labels=labels,
        n_samples=n_samples,
        hardware=hardware,
        region=region,
    )

    return EfficiencyReport(score=score, model_name=model_name)
